service_account_email=         "name@projectid.iam.gserviceaccount.com"
service_account_private_key=   "-----BEGIN PRIVATE KEY-----\nkey\n-----END PRIVATE KEY-----\n"
service_account_scopes=        ["https://www.googleapis.com/auth/admin.directory.user"]
admin_email=                   "joshua_schmidt@gapps-dev.colpal.com"
token_refresh_count=           1000
frontend_port=                 8080
backend_port=                  "http://127.0.0.1:8081"
workloc_file=                  "workloc"
empinfo_file=                  "empinfo"
orginfo_file=                  "orginfo"
test_string=                   ""
print_status_every=            25
debug_mode=                    false
update_single_account=         ""
update_from_num=               -1 #-1 to turn off
country_data_url=              "https://restcountries.eu/rest/v2/all?fields=name;alpha2Code"
country_data_file=             "countrydata"
country_mode=                  true